<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="SANDEEP" name="SanityTest_HomePage_Verification" tests="2" failures="2" timestamp="10 Jul 2016 16:23:36 GMT" time="0.095" errors="0">
  <testcase name="testmain" time="0.032" classname="Demo.Demo">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [1] but found [2]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
	expected [1] but found [2]
	at Demo.Demo.testmain(Demo.java:39)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- testmain -->
  <testcase name="testmain" time="0.079" classname="Demo.Demo">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at org.openqa.selenium.support.events.EventFiringWebDriver.extractInterfaces(EventFiringWebDriver.java:119)
	at org.openqa.selenium.support.events.EventFiringWebDriver.<init>(EventFiringWebDriver.java:91)
	at GenericLibrary.Listener.onTestFailure(Listener.java:38)
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- testmain -->
</testsuite> <!-- SanityTest_HomePage_Verification -->
