<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="SANDEEP" name="Functional_TestCases.ReviewsAndRatings.mSupply_Product_Review_Rating_007_Test" tests="1" failures="0" timestamp="10 Jul 2016 23:11:17 GMT" time="185.205" errors="1">
  <testcase name="mSupply_Product_Review_Rating_007" time="185.205" classname="Functional_TestCases.ReviewsAndRatings.mSupply_Product_Review_Rating_007_Test">
    <error type="java.lang.Exception">
      <![CDATA[java.lang.Exception
	at POM.ReviewsPage.SortedDate(ReviewsPage.java:77)
	at POM.ReviewsPage.SortedReviews(ReviewsPage.java:55)
	at POM.ProductDetailsPage.getCustomerReviews(ProductDetailsPage.java:53)
	at Functional_TestCases.ReviewsAndRatings.mSupply_Product_Review_Rating_007_Test.mSupply_Product_Review_Rating_007(mSupply_Product_Review_Rating_007_Test.java:33)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
    </error>
  </testcase> <!-- mSupply_Product_Review_Rating_007 -->
</testsuite> <!-- Functional_TestCases.ReviewsAndRatings.mSupply_Product_Review_Rating_007_Test -->
